on:
  push:
    branches:
    - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v4

    - name: Start Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        Xvfb :99 & export DISPLAY=:99
    
    - name: Build Godot
    - uses: actions/checkout@v2
    - uses: vitorgus/setup-godot@v1
      with:
        godot-version: 3.3.3
    - name: Web Build
      run: |
        mkdir -v -p build/web
        godot -v --export "HTML5" ./build/web/index.html
    - uses: actions/upload-artifact@v2
      with:
        name: web
        path: build/web
